name: node 
type: "nodejs:10"

dependencies:
  nodejs:
    sequelize-cli: "^5.1.0"

relationships:
  database: "mydatabase:postgresql"

web:
  commands:
    start: "sequelize db:migrate && node bin/www"

hooks:
  build: |
    npm install

variables:
  env:
    NODE_ENV: 'production'

disk: 512
