name: node-pg-test
type: "nodejs:10"

dependencies:
  nodejs:
    sequelize-cli: "^5.1.0"

relationship:
  database: "mydatabase:postgresql"

web:
  commands:
    start: "npm start"

hooks:
  build: |
    npm install
    sequelize db:migrate

disk: 512
